stages:
  - build
  - deploy

.build:
  image: node:26.4.0
  stage: build
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  before_script:
    - command -v pnpm || npm install --global pnpm@11.9.0
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile

build:
  extends: .build
  script:
    - pnpm run ci
    - pnpm pack
  artifacts:
    paths:
      - demo.html
      - dist/
      - albina-euregio-linea*tgz
      - LICENSE
      - package.json
      - README.md

build:cli:
  extends: .build
  script:
    - pnpm run build:cli
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_JOB_NAME_SLUG}-${CI_COMMIT_SHORT_SHA}
    paths:
      - dist/
      - LICENSE
      - package.json
      - README.md

publish-npm:
  extends: .build
  stage: deploy
  needs:
    - build
  script:
    - npm config set -- "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
    - npm config set -- "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
    - npm config set -- "${CI_API_V4_URL#https?}/groups/${CI_PROJECT_ROOT_NAMESPACE}/-/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
    - npm version --no-git-tag-version $CI_COMMIT_TAG
    - npm publish
  only:
    - tags

pages:
  stage: deploy
  image: alpine:latest
  needs:
    - build
  pages:
    publish: dist
  script:
    - echo Deploying GitLab Pages
  only:
    - tags
