---
build:
  image: node:24
  stage: build
  script:
    - corepack enable
    - yarn install --immutable
    - yarn lint
    - yarn test
    - yarn build
    - yarn pack
  artifacts:
    paths:
      - demo.html
      - dist/
      - package.tgz
      - README.md

publish-npm:
  stage: deploy
  image: node:24
  needs:
    - build
  script:
    - corepack enable
    - yarn install --immutable
    - npm config set -- "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
    - npm config set -- "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
    - npm config set -- "${CI_API_V4_URL#https?}/groups/${CI_PROJECT_ROOT_NAMESPACE}/-/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
    - npm version --no-git-tag-version $CI_COMMIT_TAG
    - npm publish
  only:
    - tags

pages:
  stage: deploy
  image: alpine:latest
  needs:
    - build
  script:
    - mv dist/ public/
    - cp exportservice.html public/exportservice.html
    - echo Deploying GitLab Pages
  artifacts:
    paths:
      - public/
  only:
    - tags
