// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot";

/**
 * Texts element with highlight and comment for the avalanche activity. Texts contains a highlight and a comment string, where highlights could also be described as a kind of headline for the longer comment. For text-formatting the HTML-Tags
 * for a new line, (
 *
 * ,) and (
 * * ,
 * * ) for lists, (
 *
 * ,
 * ===
 *
 * ) to (
 * ======
 *
 * ###### ,
 *
 * ###### ) for
 * headings and (**,**) for a bold text are allowed.
 * Texts element with highlight and comment for details on the snowpack structure.
 * Texts element with highlight and comment for travel advisory.
 * Texts element with highlight and comment for weather forecast information.
 * Texts element with highlight and comment for weather review information.
 */
export const vCaamlTexts = v.object({
  comment: v.optional(v.string()),
  highlights: v.optional(v.string()),
});

/**
 * An aspect can be defined as a set of aspects. The aspects are the expositions as in a eight part (45°) segments. The allowed aspects are the four main cardinal directions and the four intercardinal directions.
 */
export const vCaamlAspect = v.picklist(["E", "N", "NE", "NW", "n/a", "S", "SE", "SW", "W"]);

export const vCaamlAvalancheProblemCustomDataAlbina = v.object({
  avalancheType: v.string(),
});

export const vCaamlAvalancheProblemCustomData = v.object({
  ALBINA: vCaamlAvalancheProblemCustomDataAlbina,
});

/**
 * Danger rating value, according to EAWS danger scale definition.
 */
export const vCaamlDangerRatingValue = v.picklist([
  "considerable",
  "high",
  "low",
  "moderate",
  "no_rating",
  "no_snow",
  "very_high",
]);

/**
 * Elevation describes either an elevation range below a certain bound (only upperBound is set to a value) or above a certain bound (only lowerBound is set to a value). If both values are set to a value, an elevation band is defined by this property. The value uses a numeric value, not more detailed than 100m resolution. Additionally to the numeric values also 'treeline' is allowed.
 */
export const vCaamlElevationBoundaryOrBand = v.object({
  lowerBound: v.optional(v.string()),
  upperBound: v.optional(v.string()),
});

/**
 * Expected frequency of lowest snowpack stability, according to the EAWS definition. Three stage scale (few, some, many).
 */
export const vCaamlExpectedAvalancheFrequency = v.picklist(["few", "many", "none", "some"]);

/**
 * External file is used to link to external files like maps, thumbnails etc.
 */
export const vCaamlExternalFile = v.object({
  description: v.optional(v.string()),
  fileReferenceURI: v.optional(v.string()),
  fileType: v.optional(v.string()),
});

/**
 * Meta data for various uses. Can be used to link to external files like maps, thumbnails etc.
 */
export const vCaamlMetaData = v.object({
  comment: v.optional(v.string()),
  EXTFiles: v.optional(v.array(vCaamlExternalFile)),
});

/**
 * Expected avalanche problem, according to the EAWS avalanche problem definition.
 */
export const vCaamlAvalancheProblemType = v.picklist([
  "cornices",
  "favourable_situation",
  "gliding_snow",
  "new_snow",
  "no_distinct_avalanche_problem",
  "persistent_weak_layers",
  "wet_snow",
  "wind_slab",
]);

/**
 * Expected avalanche type.
 */
export const vCaamlAvalancheTypeType = v.picklist(["slab", "loose", "glide"]);

/**
 * Snowpack stability, according to the EAWS definition. Four stage scale (very poor, poor, fair, good).
 */
export const vCaamlExpectedSnowpackStability = v.picklist(["fair", "good", "poor", "very_poor"]);

/**
 * Valid time period can be used to limit the validity of an element to an earlier or later period. It can be used to distinguish danger ratings or avalanche problems.
 */
export const vCaamlValidTimePeriod = v.picklist(["all_day", "earlier", "later"]);

/**
 * Defines an avalanche problem, its time, aspect, and elevation constraints. A textual detail about the affected terrain can be given in the comment field. Also, details about the expected avalanche size, snowpack stability and its frequency can be defined. The implied danger rating value is optional.
 */
export const vCaamlAvalancheProblem = v.object({
  aspects: v.optional(v.array(vCaamlAspect)),
  avalancheSize: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
      v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
    ),
  ),
  comment: v.optional(v.string()),
  customData: v.optional(vCaamlAvalancheProblemCustomData),
  dangerRatingValue: v.optional(vCaamlDangerRatingValue),
  elevation: v.optional(vCaamlElevationBoundaryOrBand),
  frequency: v.optional(vCaamlExpectedAvalancheFrequency),
  metaData: v.optional(vCaamlMetaData),
  problemType: v.optional(vCaamlAvalancheProblemType),
  avalancheType: v.optional(vCaamlAvalancheTypeType),
  snowpackStability: v.optional(vCaamlExpectedSnowpackStability),
  validTimePeriod: v.optional(vCaamlValidTimePeriod),
});

export const vCaamlAvalancheBulletinCustomDataBulletinPhoto = v.object({
  url: v.string(),
  copyright: v.optional(v.string()),
  date: v.optional(v.pipe(v.string(), v.isoDate())),
  microRegionId: v.optional(v.string()),
  locationName: v.optional(v.string()),
  latitude: v.optional(v.number()),
  longitude: v.optional(v.number()),
});

export const vCaamlAvalancheBulletinCustomDataAlbina = v.object({
  mainDate: v.string(),
  bulletinPhotos: v.array(vCaamlAvalancheBulletinCustomDataBulletinPhoto),
});

export const vCaamlAvalancheBulletinCustomDataLwdTyrol = v.object({
  dangerPatterns: v.array(v.string()),
});

export const vCaamlAvalancheBulletinCustomData = v.object({
  ALBINA: vCaamlAvalancheBulletinCustomDataAlbina,
  LWD_Tyrol: vCaamlAvalancheBulletinCustomDataLwdTyrol,
});

/**
 * Defines a danger rating, its elevation constraints and the valid time period. If validTimePeriod or elevation are constrained for a rating, it is expected to define a dangerRating for all the other cases.
 */
export const vCaamlDangerRating = v.object({
  aspects: v.optional(v.array(vCaamlAspect)),
  customData: v.optional(v.record(v.string(), v.unknown())),
  elevation: v.optional(vCaamlElevationBoundaryOrBand),
  mainValue: v.optional(vCaamlDangerRatingValue),
  metaData: v.optional(vCaamlMetaData),
  validTimePeriod: v.optional(vCaamlValidTimePeriod),
});

/**
 * Region element describes a (micro) region. The regionID follows the EAWS schema. It is recommended to have the region shape's files with the same IDs in gitlab.com/eaws/eaws-regions. Additionally, the region name can be added.
 */
export const vCaamlRegion = v.object({
  customData: v.optional(v.record(v.string(), v.unknown())),
  metaData: v.optional(vCaamlMetaData),
  name: v.optional(v.string()),
  regionID: v.optional(v.string()),
});

/**
 * Details on a person.
 */
export const vCaamlPerson = v.object({
  customData: v.optional(v.record(v.string(), v.unknown())),
  metaData: v.optional(vCaamlMetaData),
  name: v.optional(v.string()),
  website: v.optional(v.string()),
});

/**
 * Information about the bulletin provider. Defines the name, website and/or contactPerson (which could be the author) of the issuing AWS.
 */
export const vCaamlAvalancheBulletinProvider = v.object({
  contactPerson: v.optional(vCaamlPerson),
  customData: v.optional(v.record(v.string(), v.unknown())),
  metaData: v.optional(vCaamlMetaData),
  name: v.optional(v.string()),
  website: v.optional(v.string()),
});

/**
 * Details about the issuer/AWS of the bulletin. Information about the bulletin source. Either as in a person or with a provider element to specify details about the AWS.
 */
export const vCaamlAvalancheBulletinSource = v.object({
  person: v.optional(vCaamlPerson),
  provider: v.optional(vCaamlAvalancheBulletinProvider),
});

export const vCaamlTendencyType = v.picklist(["decreasing", "increasing", "steady"]);

/**
 * Valid time defines two ISO 8601 timestamps in UTC or with time zone information. Date and Time from and until this bulletin is valid. ISO 8601 Timestamp in UTC or with time zone information.
 */
export const vCaamlValidTime = v.object({
  endTime: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  startTime: v.optional(v.pipe(v.string(), v.isoTimestamp())),
});

/**
 * Texts element with highlight and comment for the avalanche activity. Texts contains a highlight and a comment string, where highlights could also be described as a kind of headline for the longer comment. For text-formatting the HTML-Tags
 * for a new line, (
 *
 * ,) and (
 * * ,
 * * ) for lists, (
 *
 * ,
 * ===
 *
 * ) to (
 * ======
 *
 * ###### ,
 *
 * ###### ) for
 * headings and (**,**) for a bold text are allowed.
 * Texts element with highlight and comment for details on the snowpack structure.
 * Texts element with highlight and comment for travel advisory.
 * Texts element with highlight and comment for weather forecast information.
 * Texts element with highlight and comment for weather review information.
 * Describes the expected tendency of the development of the avalanche situation for a
 * defined time period.
 */
export const vCaamlTendency = v.object({
  comment: v.optional(v.string()),
  highlights: v.optional(v.string()),
  customData: v.optional(v.record(v.string(), v.unknown())),
  metaData: v.optional(vCaamlMetaData),
  tendencyType: v.optional(vCaamlTendencyType),
  validTime: v.optional(vCaamlValidTime),
});

/**
 * Avalanche Bulletin valid for a given set of regions.
 */
export const vCaamlAvalancheBulletin = v.object({
  avalancheActivity: v.optional(vCaamlTexts),
  avalancheProblems: v.optional(v.array(vCaamlAvalancheProblem)),
  bulletinID: v.optional(v.string()),
  customData: v.optional(vCaamlAvalancheBulletinCustomData),
  dangerRatings: v.optional(v.array(vCaamlDangerRating)),
  highlights: v.optional(v.string()),
  lang: v.optional(v.string()),
  metaData: v.optional(vCaamlMetaData),
  nextUpdate: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  publicationTime: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  regions: v.optional(v.array(vCaamlRegion)),
  snowpackStructure: v.optional(vCaamlTexts),
  source: v.optional(vCaamlAvalancheBulletinSource),
  tendency: v.optional(v.array(vCaamlTendency)),
  travelAdvisory: v.optional(vCaamlTexts),
  unscheduled: v.optional(v.boolean()),
  validTime: v.optional(vCaamlValidTime),
  weatherForecast: v.optional(vCaamlTexts),
  weatherReview: v.optional(vCaamlTexts),
});

export const vAbstractPersistentObject = v.object({
  id: v.nullish(v.string()),
});

/**
 * This class holds all information about one danger source.
 */
export const vDangerSource = v.intersect([
  vAbstractPersistentObject,
  v.object({
    id: v.nullish(v.string()),
    ownerRegion: v.optional(v.string()),
    creationDate: v.optional(v.pipe(v.string(), v.isoTimestamp())),
    title: v.optional(v.string()),
    description: v.optional(v.string()),
  }),
]);

export const vDangerSourceVariantStatus = v.picklist(["active", "dormant", "inactive"]);

export const vDangerSourceVariantType = v.picklist(["forecast", "analysis"]);

export const vAvalancheType = v.picklist(["slab", "loose", "glide"]);

export const vAspect = v.picklist(["N", "NE", "E", "SE", "S", "SW", "W", "NW"]);

export const vDaytime = v.picklist([
  "evening",
  "first_night_half",
  "second_night_half",
  "morning",
  "forenoon",
  "afternoon",
]);

export const vSlopeGradient = v.picklist([
  "moderately_steep",
  "steep",
  "very_steep",
  "extremely_steep",
]);

export const vProbability = v.picklist(["likely", "possible", "unlikely"]);

export const vDangerSign = v.picklist([
  "shooting_cracks",
  "whumpfing",
  "fresh_avalanches",
  "glide_cracks",
]);

export const vDangerRating = v.picklist([
  "missing",
  "no_snow",
  "no_rating",
  "low",
  "moderate",
  "considerable",
  "high",
  "very_high",
]);

export const vDangerRatingModificator = v.picklist(["none", "minus", "equal", "plus"]);

export const vAvalancheSize = v.picklist(["small", "medium", "large", "very_large", "extreme"]);

export const vSnowpackStability = v.picklist(["good", "fair", "poor", "very_poor"]);

export const vFrequency = v.picklist(["none", "few", "some", "many"]);

export const vEawsMatrixInformation = v.object({
  dangerRating: v.optional(vDangerRating),
  dangerRatingModificator: v.optional(vDangerRatingModificator),
  avalancheSize: v.optional(vAvalancheSize),
  snowpackStability: v.optional(vSnowpackStability),
  frequency: v.optional(vFrequency),
  avalancheSizeValue: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
      v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
    ),
  ),
  snowpackStabilityValue: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
      v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
    ),
  ),
  frequencyValue: v.optional(
    v.pipe(
      v.number(),
      v.integer(),
      v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
      v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
    ),
  ),
});

export const vGlidingSnowActivity = v.picklist(["low", "medium", "high"]);

export const vGrainShape = v.picklist([
  "PP",
  "MM",
  "DF",
  "RG",
  "FC",
  "DH",
  "SH",
  "MF",
  "IF",
  "PPco",
  "PPnd",
  "PPpl",
  "PPsd",
  "PPir",
  "PPgp",
  "PPhl",
  "PPip",
  "PPrm",
  "MMrp",
  "MMci",
  "DFdc",
  "DFbk",
  "RGsr",
  "RGlr",
  "RGwp",
  "RGxf",
  "FCso",
  "FCsf",
  "FCxr",
  "DHcp",
  "DHpr",
  "DHch",
  "DHla",
  "DHxr",
  "SHsu",
  "SHcv",
  "SHxr",
  "MFcl",
  "MFpc",
  "MFsl",
  "MFcr",
  "IFil",
  "IFic",
  "IFbi",
  "IFrc",
  "IFsc",
]);

export const vHandHardness = v.picklist([
  "fist",
  "four_fingers",
  "one_finger",
  "pencil",
  "knife",
  "ice",
]);

export const vTendency = v.picklist(["decreasing", "steady", "increasing"]);

export const vCharacteristic = v.picklist(["low", "medium", "high", "very_high"]);

export const vDistribution = v.picklist(["isolated", "specific", "widespread"]);

export const vThickness = v.picklist(["thick", "thin"]);

export const vCrust = v.picklist(["no", "partly", "yes"]);

export const vSnowpackPosition = v.picklist(["upper", "middle", "lower", "ground"]);

export const vCreationProcess = v.picklist([
  "radiation_recrystallization",
  "diurnal_recrystallization",
  "melt_layer_recrystallization",
  "surface_hoar_formation",
]);

export const vRecognizability = v.picklist(["very_easy", "easy", "hard", "very_hard"]);

export const vTerrainType = v.picklist([
  "gullies_and_bowls",
  "adjacent_to_ridgelines",
  "distant_from_ridgelines",
  "in_the_vicinity_of_peaks",
  "pass_areas",
  "shady_slopes",
  "sunny_slopes",
  "grassy_slopes",
  "cut_slopes",
  "wind_loaded_slopes",
  "base_of_rock_walls",
  "behind_abrupt_changes_in_the_terrain",
  "transitions_into_gullies_and_bowls",
  "areas_where_the_snow_cover_is_rather_shallow",
  "transitions_from_a_shallow_to_a_deep_snowpack",
  "highly_frequented_off_piste_terrain",
  "little_used_backcountry_terrain",
  "places_that_are_protected_from_the_wind",
  "regions_exposed_to_the_foehn_wind",
  "regions_with_a_lot_of_snow",
  "regions_exposed_to_precipitation",
  "regions_exposed_to_heavier_precipitation",
]);

export const vWetness = v.picklist(["wet", "moist", "dry"]);

/**
 * This class holds all information about one danger source variant.
 */
export const vDangerSourceVariant = v.intersect([
  vAbstractPersistentObject,
  v.object({
    id: v.nullish(v.string()),
    originalDangerSourceVariantId: v.optional(v.string()),
    forecastDangerSourceVariantId: v.optional(v.string()),
    dangerSource: v.nullish(vDangerSource),
    title: v.optional(v.string()),
    creationDate: v.optional(v.pipe(v.string(), v.isoTimestamp())),
    updateDate: v.optional(v.pipe(v.string(), v.isoTimestamp())),
    validFrom: v.optional(v.pipe(v.string(), v.isoTimestamp())),
    validUntil: v.optional(v.pipe(v.string(), v.isoTimestamp())),
    dangerSourceVariantStatus: v.optional(vDangerSourceVariantStatus),
    dangerSourceVariantType: v.optional(vDangerSourceVariantType),
    ownerRegion: v.optional(v.string()),
    regions: v.optional(v.array(v.string())),
    hasDaytimeDependency: v.optional(v.boolean()),
    avalancheType: v.optional(vAvalancheType),
    aspects: v.optional(v.array(vAspect)),
    elevationHigh: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    treelineHigh: v.optional(v.boolean()),
    elevationLow: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    treelineLow: v.optional(v.boolean()),
    aspectsOfExistence: v.optional(v.array(vAspect)),
    elevationHighOfExistence: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    treelineHighOfExistence: v.optional(v.boolean()),
    elevationLowOfExistence: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    treelineLowOfExistence: v.optional(v.boolean()),
    dangerIncreaseWithElevation: v.optional(v.boolean()),
    highestDangerAspect: v.optional(vAspect),
    dangerPeak: v.optional(vDaytime),
    slopeGradient: v.optional(vSlopeGradient),
    runoutIntoGreen: v.optional(v.boolean()),
    penetrateDeepLayers: v.optional(v.boolean()),
    naturalRelease: v.optional(vProbability),
    dangerSigns: v.optional(v.array(vDangerSign)),
    eawsMatrixInformation: v.optional(vEawsMatrixInformation),
    comment: v.optional(v.string()),
    textcat: v.optional(v.string()),
    uncertainty: v.optional(v.string()),
    glidingSnowActivity: v.optional(vGlidingSnowActivity),
    glidingSnowActivityValue: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    snowHeightUpperLimit: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    snowHeightLowerLimit: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    snowHeightAverage: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    zeroDegreeIsotherm: v.optional(v.boolean()),
    slabGrainShape: v.optional(vGrainShape),
    slabThicknessUpperLimit: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    slabThicknessLowerLimit: v.optional(
      v.pipe(
        v.number(),
        v.integer(),
        v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
        v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
      ),
    ),
    slabHandHardnessUpperLimit: v.optional(vHandHardness),
    slabHandHardnessLowerLimit: v.optional(vHandHardness),
    slabHardnessProfile: v.optional(vTendency),
    slabEnergyTransferPotential: v.optional(vCharacteristic),
    slabDistribution: v.optional(vDistribution),
    weakLayerGrainShapes: v.optional(v.array(vGrainShape)),
    weakLayerGrainSizeUpperLimit: v.optional(v.number()),
    weakLayerGrainSizeLowerLimit: v.optional(v.number()),
    weakLayerPersistent: v.optional(v.boolean()),
    weakLayerThickness: v.optional(vThickness),
    weakLayerStrength: v.optional(vCharacteristic),
    weakLayerWet: v.optional(v.boolean()),
    weakLayerCrustAbove: v.optional(vCrust),
    weakLayerCrustBelow: v.optional(vCrust),
    weakLayerPosition: v.optional(vSnowpackPosition),
    weakLayerCreation: v.optional(vCreationProcess),
    weakLayerDistribution: v.optional(vDistribution),
    dangerSpotRecognizability: v.optional(vRecognizability),
    remoteTriggering: v.optional(vProbability),
    terrainTypes: v.optional(v.array(vTerrainType)),
    looseSnowGrainShape: v.optional(vGrainShape),
    looseSnowMoisture: v.optional(vWetness),
  }),
]);
